apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: mongo.3cd80d1a9ec844598ced.westus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: mongodb-svc
          servicePort: 27017
        path: /
  - host: todo.3cd80d1a9ec844598ced.westus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: todo
          servicePort: 3000
        path: /